<?php
return [
    "itemPerPage"=>25,
    "permission"=> [
        "statistics"=>         [                               "view"=>1],
        "users"=>              ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "drivers"=>              ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "notifications"=>      ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "contacts"=>           [                   "delete"=>1,"view"=>1],
        "categories"=>         ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "products"=>           ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "stores"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "regions"=>            ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "ads"=>                ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "points"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "faqs"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "orders"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "admins"=>             [                               "view"=>1],
        "appInfo"=>            [         "edit"=>1,            "view"=>1],
    ],
    "closedModule"=>[
        "statistics"=>         [                               "view"=>1],
        "users"=>              ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "notifications"=>      ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "contacts"=>           [                   "delete"=>1,"view"=>1],
        "price_list"=>         ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "stores"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "regions"=>            ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "ads"=>                ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "codes"=>              ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "bank_accounts"=>      ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "points"=>             ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "faqs"=>               ["add"=>1,"edit"=>1,"delete"=>1,"view"=>1],
        "admins"=>             [                               "view"=>1],
        "appInfo"=>            [         "edit"=>1,            "view"=>1],
    ],
];